@startuml
skinparam componentStyle uml2

package "Склад" {
    [Информационная система] as IS
}

IS - [Учет поступления товаров]
IS - [Учет ухода товаров]
IS - [Списание товаров со склада]
IS - [Место хранения товара на складе]
IS - [Учет товара на складе]

[Учет поступления товаров] ..> [Учет товара на складе] : содержит
[Учет ухода товаров] ..> [Учет товара на складе] : содержит
[Списание товаров со склада] ..> [Учет товара на складе] : содержит
[Место хранения товара на складе] ..> [Учет товара на складе] : содержит

@enduml