@startuml
allowmixing

actor Пользователь
entity Склад
entity Товар
entity МестоХранения

Пользователь -> Склад : добавить товар
Склад -> Товар : создать
Товар -> МестоХранения : выбрать место хранения
МестоХранения --> Склад : подтвердить
Склад --> Пользователь : подтвердить добавление

Пользователь -> Склад : удалить товар
Склад --> Пользователь : подтвердить удаление

@enduml
