@startuml
allowmixing

node Пользователь

node "Информационная система склада" {
    component Склад
    component Товар
    component МестоХранения
}

node "База данных" as БД
node "Сервер приложений" as Сервер

Пользователь --> Сервер : HTTP запрос
Сервер --> БД : Запрос к базе данных
Сервер --> Склад : Обработка данных
Склад --> Товар : Работа с товарами
Склад --> МестоХранения : Работа с местами хранения

@enduml
