@startuml
allowmixing

actor Работник
entity Склад
entity Товар
entity МестоХранения

Работник -> Склад : добавить товар
Склад -> Товар : создать
Товар -> МестоХранения : выбрать место хранения
МестоХранения --> Склад : подтвердить
Склад --> Работник : подтвердить добавление

Работник -> Склад : удалить товар
Склад --> Работник : подтвердить удаление

@enduml
